sudo: required
services:
    - docker

before_install:
    - docker build -t jeremycod/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true jeremycod/react-test npm test

after_success:
    - docker build -t jeremycod/multi-client ./client
    - docker build -t jeremycod/multi-nginx ./nginx
    - docker build -t jeremycod/multi-server ./server
    - docker build -t jeremycod/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Take those images and push them to docker hub
    - docker push jeremycod/multi-client
    - docker push jeremycod/multi-nginx
    - docker push jeremycod/multi-server
    - docker push jeremycod/multi-worker

deploy:
    provider: elasticbeanstalk
    region: 'us-east-1'
    app: 'multi-docker'
    env: 'MultiDocker-env'
    bucket_name: 'elasticbeanstalk-us-east-1-885360335839'
    bucket_path: 'docker-multi'
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    